---
title: "HW 3"
author: "Melanie Mayer"
date: "10/10/2018"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

```

## Question 1

```{r q1}

brfss_data = brfss_smart2010 %>%
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>%
  separate(locationdesc, into = c("remove", "county"), sep = " - ") %>%
  select(-c(remove)) %>%
  rename(state = locationabbr) %>%
  mutate(response = factor(response, 
                           levels = c("Excellent", "Very good", "Good", "Fair", "Poor")))


brfss_data %>%
  filter(year == 2002) %>%
  distinct(county, .keep_all = T) %>%
  group_by(state) %>%
  summarize(n = n()) %>%
  filter(n == 7) %>%
  knitr::kable()

#During 2002, the only three states which had data on exactly seven counties were Connecticut, Florida, and Massachusetts


brfss_data %>% 
  distinct(county, year, .keep_all = TRUE) %>%
  select(c(year, state, county)) %>%
  group_by(state, year) %>%
  summarize(locations = n()) %>%
  ggplot(aes(x = year, y = locations, color = state)) +
    geom_line()

#This plot does not seem to be a good choice for this data set. It is hard to enterpret anything from the graphic, it may be better to try and look into each state on its own rather than comparing them all on one plot.


brfss_data %>%
  filter(year %in% c(2002, 2006, 2010), state == "NY", response == "Excellent") %>%
  group_by(year) %>%
  summarize(mean = mean(data_value, na.rm = T),
            sd = sd(data_value, na.rm = T)) %>%
  knitr::kable()

#It appears the mean did not change too much through the years, the standard deviation does however decrease.

brfss_data %>%
  group_by(year, state, response) %>%
  summarize(mean = mean(data_value, na.rm = T)) %>%
  ggplot(aes(x = year, y = mean)) +
  geom_point(alpha = 0.5) +
  theme(axis.text.x = element_text(angle = 50, hjust = 1)) +
  facet_grid(. ~ response)

#The proportion per each response appears to be consistant accross all the years


```

## Question 2

This data consists of `r nrow(instacart)` observations over `r ncol(instacart)` variables.

There are `r instacart %>% distinct(aisle_id) %>% nrow()` distinct isles. 


```{r q2}

instacart %>% 
  distinct(aisle_id) %>%
  nrow()

instacart %>%
  group_by(aisle) %>%
  count(aisle) %>%
  arrange(-n) %>%
  head(5) %>%
  knitr::kable()

instacart_plot1 = instacart %>%
  mutate(aisle_id = factor(aisle_id, levels = c(1:134))) %>%
  filter(aisle_id %in% c(1:67)) %>%
  mutate(aisle_id = as.numeric(aisle_id)) %>%
  group_by(aisle_id) %>%
  count() %>%
  ggplot(aes(x = aisle_id, y = n)) +
  geom_point() +
  scale_x_continuous(breaks = seq(0, 67, 5))


instacart_plot2 = instacart %>%
  mutate(aisle_id = factor(aisle_id, levels = c(1:134))) %>%
  filter(aisle_id %in% c(68:134)) %>%
  mutate(aisle_id = as.numeric(aisle_id)) %>%
  group_by(aisle_id) %>%
  count() %>%
  ggplot(aes(x = aisle_id, y = n)) +
  geom_point() +
  scale_x_continuous(breaks = seq(68, 134, 5))

instacart_plot1 / instacart_plot2


instacart %>%
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>%
  group_by(aisle) %>%
  count(product_name) %>%
  top_n(5) %>%
  knitr::kable()


instacart %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  summarize(mean_time_of_day = mean(order_hour_of_day)) %>%
  spread(key = product_name, value = mean_time_of_day) %>%
  mutate(order_dow = order_dow + 1,
         order_dow = DescTools::day.name[order_dow]) %>%
  knitr::kable()
  
```


## Question 3

```{r q3}

ny_noaa_clean = ny_noaa %>%
  janitor::clean_names() %>%
  separate(date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(year = factor(year),
         tmax = as.numeric(tmax)/10, 
         tmin = as.numeric(tmin)/10)

ny_noaa_clean %>%
  count(snow) %>%
  top_n(5) %>%
  knitr::kable()

ny_noaa_clean %>%
  filter(month %in% c("01", "07")) %>%
  group_by(month, id, year) %>%
  summarize(mean_tmax = mean(tmax, na.rm = TRUE)) %>%
  ggplot(aes(x = year, y = mean_tmax)) +
    geom_point(alpha = 0.5) +
    theme(axis.text.x = element_text(angle = 75, hjust = 1)) +
    facet_grid(. ~ month)


tmax_vs_tmin = ny_noaa_clean %>%
  ggplot(aes(x = tmax, y = tmin)) +
  geom_point()

snow_per_year = ny_noaa_clean %>%
  filter(snow %in% c(1:99)) %>%
  group_by(year) %>%
  ggplot(aes(x = snow)) +
  geom_histogram()

tmax_vs_tmin + snow_per_year

```




